---
apiVersion: v1
kind: Namespace
metadata:
  name: dwk-project
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dwk-project
  namespace: dwk-project
spec:
  interval: 1m
  path: "./project"
  prune: true
  sourceRef:
    kind: GitRepository
    name: dwk-2021
    namespace: flux-system
