---
apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3s-dwk
agents: 2
image: docker.io/rancher/k3s:v1.21.1-k3s1
ports:
  - port: 9090:80
    nodeFilters:
      - loadbalancer
  - port: 9091:30080
    nodeFilters:
      - agent[0]
  - port: 9092:30080
    nodeFilters:
      - agent[1]
options:
  k3s:
    # https://github.com/rancher/k3d/issues/133#issuecomment-770418986
    extraServerArgs:
      - --kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%
      - --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%
